### ISSUE TITLE
Cannot resolve "Setten/Queue" namespace from the IoC Container

### ISSUE THREAD

**Issue by tnet-dspangenberg** [RomainLanz/adonis-bull-queue#22]
Hi,

starting the queue  with`node ace queue:listen` leads to IocLookupException: E_IOC_LOOKUP_FAILED: Cannot resolve "Setten/Queue" namespace from the IoC Container.

Best regards,
Danny

**Comment by RomainLanz** [comment]
Hey @tnet-dspangenberg! 👋🏻 

What version are you using?

**Comment by tnet-dspangenberg** [comment]
I'm using 1.0.2 and probably it's 

https://github.com/RomainLanz/adonis-bull-queue/blob/aa027f2363fd255daf16c4c43854226d924cee8e/commands/QueueListener.ts#L23

**Comment by RomainLanz** [comment]
Whoops, I miss that one.

Can you please upgrade to `1.0.3` and try again?

**Comment by tnet-dspangenberg** [comment]
Looks good, thank you for the quick response.

**Comment by RomainLanz** [comment]
Nice, happy coding!
