### ISSUE TITLE
Set up the library

### ISSUE THREAD

**Issue by rutonyru** [RomainLanz/adonis-bull-queue#43]
Hi @RomainLanz,
After the first command to install your library (and upgrade vinejs to 2.0.0), I wasn't able to launch the next one to create a specific job : `node ace make:job myJob`
I tried two more commands :
* `node ace configure @rlanz/bull-queue` (as it is done in the repository : https://github.com/acidiney/bull-queue
* `node ace make:job {job]`
And then it works : `node ace make:job myJob`
Could it be something to add to Readme ?
Good night,
Antoine

**Comment by RomainLanz** [comment]
Hey @rutonyru! 👋🏻 

Do you encounter any error when running the `node ace make:job` command?

**Comment by rutonyru** [comment]
Hi @RomainLanz ,
![image](https://github.com/RomainLanz/adonis-bull-queue/assets/11994958/3fb8d47a-ed51-4eed-b3fe-d968d0e2d5ea)
I tried to copy/paste a screen of my console. Can you see it ?
Antoine

**Comment by RomainLanz** [comment]
The readme say to install the package using `node ace add`, which automatically run the `configure` command.

**Comment by rutonyru** [comment]
You're completely right. I switch to npm install to try to understand why I got error during `node ace add`.
