### ISSUE TITLE
How to use it on Cleavr.io

### ISSUE THREAD

**Issue by rhnkyr** [RomainLanz/adonis-bull-queue#50]
Hi,

I added a deployment hook but not sure what to exec

`node build/ace queue:listen` or `pm2 start build/ace queue:listen `

any input appreciated. Thanks in advance.

**Comment by anishghimire862** [comment]
Hello @rhnkyr,

We've already discussed this on Discord.

For future travelers, you can create a Process Monitor (https://docs.cleavr.io/process-monitors/) with the following command:

node /home/{{ user }}/{{ site }}/current/build/ace queue:listen

Please replace the placeholder {{ user }} with the actual server user your site is associated with, and {{ site }} with your domain name, such as example.com.

If possible, we should create a custom deployment hook (https://docs.cleavr.io/deployment-hooks/) to terminate/stop the service. The Process Monitor/Supervisor should be able to restart the service.
